Page({
    data:{
       myCollection:''
    },
    onShow:function(){
        this.setData({
           myCollection:wx.getStorageSync("myCollection")
        });
        console.log(this.data.myCollection);
    }
})